version: '2'

services:

  # database service
  db:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    command: --smallfiles

  # message queue service
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  # celery worker service for flask application
  celery:
    image: flask-scaffolding:assessment
    env_file:
      local.env
    command: >
      /bin/ash -c "
      celery worker -A app.celery --loglevel=info
      "
    volumes:
      - ./src/:/code
      - ./logs:/var/log/scaffolding
    depends_on:
      - db
      - rabbitmq

  # web service for flask application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-scaffolding:assessment
    env_file:
      local.env
    command: >
      /bin/ash -c "
        flask run --host=0.0.0.0
      "
    volumes:
      - ./src/:/code
      - ./logs:/var/log/scaffolding
    ports:
      - "8400:5000"
    depends_on:
      - db
      - celery
      - rabbitmq
